import { Ionicons } from '@react-native-vector-icons/ionicons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, View } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { YuzuHeader, YuzuScreen, yuzuColors, yuzuText } from '@/components/yuzu-screen';

const methods = [['search-outline', 'Search by ingredients'], ['logo-tiktok', 'From social'], ['image-outline', 'Photo · screenshot or saved photo'], ['camera-outline', 'Photo of a dish'], ['sparkles-outline', 'Ask AI for a recipe'], ['document-text-outline', 'Paste a recipe · from text'], ['chatbubble-ellipses-outline', 'Chat with AI']];

export default function AddRecipeScreen() {
  return <YuzuScreen><YuzuHeader title="Add a recipe" onBack={() => router.back()} /><View style={styles.fast}><ThemedText style={styles.fastLabel}>FASTEST WAY</ThemedText><View style={styles.input}><Ionicons name="link-outline" size={17} color={yuzuColors.muted} /><ThemedText style={styles.placeholder}>Paste a TikTok, YouTube, or recipe link</ThemedText></View></View><ThemedText style={styles.choose}>OR CHOOSE ANOTHER WAY</ThemedText><View style={styles.methods}>{methods.map(([icon, label]) => <Pressable key={label} style={styles.method} onPress={() => router.push('/recipe/preview')}><View style={styles.iconBox}><Ionicons name={icon as never} size={17} color={yuzuColors.leaf} /></View><ThemedText style={styles.methodText}>{label}</ThemedText><Ionicons name="chevron-forward" size={15} color={yuzuColors.muted} /></Pressable>)}</View><Pressable style={styles.manual} onPress={() => router.push('/recipe/preview')}><Ionicons name="create-outline" size={16} color={yuzuColors.leaf} /><ThemedText style={styles.manualText}>Add manually</ThemedText></Pressable><ThemedText style={styles.note}>Your recipes stay private and organized in yuzu.</ThemedText></YuzuScreen>;
}

const styles = StyleSheet.create({ fast: { backgroundColor: yuzuColors.ink, borderRadius: 16, padding: 12, gap: 7 }, fastLabel: { color: yuzuColors.sun, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, input: { height: 44, borderRadius: 10, backgroundColor: '#fff', alignItems: 'center', flexDirection: 'row', gap: 7, paddingHorizontal: 10 }, placeholder: { color: yuzuColors.muted, fontSize: 16 }, choose: { color: yuzuColors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginTop: 2 }, methods: { gap: 7 }, method: { minHeight: 48, borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: yuzuColors.line, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 9 }, iconBox: { width: 30, height: 30, borderRadius: 8, backgroundColor: yuzuColors.sage, alignItems: 'center', justifyContent: 'center' }, methodText: { color: yuzuColors.ink, fontSize: 16, fontWeight: '700', flex: 1 }, manual: { minHeight: 48, borderRadius: 12, backgroundColor: yuzuColors.sage, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 }, manualText: { color: yuzuColors.leaf, fontSize: 16, fontWeight: '800' }, note: { color: yuzuColors.muted, fontSize: 12, marginTop: 'auto' } });
