// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_account_id", Type: field.TypeString},
		{Name: "access_token", Type: field.TypeString, Nullable: true},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "user_accounts", Type: field.TypeInt},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_users_accounts",
				Columns:    []*schema.Column{AccountsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "account_provider_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[1], AccountsColumns[2]},
			},
		},
	}
	// FoldersColumns holds the columns for the "folders" table.
	FoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt},
	}
	// FoldersTable holds the schema information for the "folders" table.
	FoldersTable = &schema.Table{
		Name:       "folders",
		Columns:    FoldersColumns,
		PrimaryKey: []*schema.Column{FoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "folders_users_folders",
				Columns:    []*schema.Column{FoldersColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "folder_user_id",
				Unique:  false,
				Columns: []*schema.Column{FoldersColumns[2]},
			},
		},
	}
	// GroceriesColumns holds the columns for the "groceries" table.
	GroceriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "unit", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeFloat64, Nullable: true},
		{Name: "tag", Type: field.TypeString, Nullable: true},
		{Name: "checked", Type: field.TypeBool, Default: false},
		{Name: "recipe_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// GroceriesTable holds the schema information for the "groceries" table.
	GroceriesTable = &schema.Table{
		Name:       "groceries",
		Columns:    GroceriesColumns,
		PrimaryKey: []*schema.Column{GroceriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groceries_recipes_groceries",
				Columns:    []*schema.Column{GroceriesColumns[6]},
				RefColumns: []*schema.Column{RecipesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "groceries_users_groceries",
				Columns:    []*schema.Column{GroceriesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "grocery_user_id",
				Unique:  false,
				Columns: []*schema.Column{GroceriesColumns[7]},
			},
		},
	}
	// RecipesColumns holds the columns for the "recipes" table.
	RecipesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "servings", Type: field.TypeInt},
		{Name: "process_minutes", Type: field.TypeInt},
		{Name: "ingredients", Type: field.TypeJSON},
		{Name: "instructions", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "text[]"}},
		{Name: "tags", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "text[]"}},
		{Name: "import_status", Type: field.TypeEnum, Enums: []string{"looking", "making", "done", "failed"}, Default: "done"},
		{Name: "import_error", Type: field.TypeString, Nullable: true},
		{Name: "processing_at", Type: field.TypeTime, Nullable: true},
		{Name: "import_webhook", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "rating", Type: field.TypeFloat64, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "image_s3_key", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "webhook_id", Type: field.TypeString, Nullable: true},
		{Name: "raw_source_payload", Type: field.TypeJSON, Nullable: true},
		{Name: "folder_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RecipesTable holds the schema information for the "recipes" table.
	RecipesTable = &schema.Table{
		Name:       "recipes",
		Columns:    RecipesColumns,
		PrimaryKey: []*schema.Column{RecipesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recipes_folders_recipes",
				Columns:    []*schema.Column{RecipesColumns[19]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "recipes_users_recipes",
				Columns:    []*schema.Column{RecipesColumns[20]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "recipe_user_id",
				Unique:  false,
				Columns: []*schema.Column{RecipesColumns[20]},
			},
			{
				Name:    "recipe_folder_id",
				Unique:  false,
				Columns: []*schema.Column{RecipesColumns[19]},
			},
			{
				Name:    "recipe_webhook_id",
				Unique:  false,
				Columns: []*schema.Column{RecipesColumns[17]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_refresh_tokens", Type: field.TypeInt},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "picture", Type: field.TypeString, Nullable: true},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		FoldersTable,
		GroceriesTable,
		RecipesTable,
		RefreshTokensTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = UsersTable
	FoldersTable.ForeignKeys[0].RefTable = UsersTable
	GroceriesTable.ForeignKeys[0].RefTable = RecipesTable
	GroceriesTable.ForeignKeys[1].RefTable = UsersTable
	RecipesTable.ForeignKeys[0].RefTable = FoldersTable
	RecipesTable.ForeignKeys[1].RefTable = UsersTable
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
}
