// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danirisdiandita/malas-monorepo/api/ent/grocery"
	"github.com/danirisdiandita/malas-monorepo/api/ent/predicate"
	"github.com/danirisdiandita/malas-monorepo/api/ent/recipe"
	"github.com/danirisdiandita/malas-monorepo/api/ent/user"
	"github.com/google/uuid"
)

// GroceryUpdate is the builder for updating Grocery entities.
type GroceryUpdate struct {
	config
	hooks    []Hook
	mutation *GroceryMutation
}

// Where appends a list predicates to the GroceryUpdate builder.
func (_u *GroceryUpdate) Where(ps ...predicate.Grocery) *GroceryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GroceryUpdate) SetUserID(v int) *GroceryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableUserID(v *int) *GroceryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *GroceryUpdate) SetName(v string) *GroceryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableName(v *string) *GroceryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *GroceryUpdate) SetUnit(v string) *GroceryUpdate {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableUnit(v *string) *GroceryUpdate {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *GroceryUpdate) SetQuantity(v float64) *GroceryUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableQuantity(v *float64) *GroceryUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *GroceryUpdate) AddQuantity(v float64) *GroceryUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// ClearQuantity clears the value of the "quantity" field.
func (_u *GroceryUpdate) ClearQuantity() *GroceryUpdate {
	_u.mutation.ClearQuantity()
	return _u
}

// SetTag sets the "tag" field.
func (_u *GroceryUpdate) SetTag(v string) *GroceryUpdate {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableTag(v *string) *GroceryUpdate {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *GroceryUpdate) ClearTag() *GroceryUpdate {
	_u.mutation.ClearTag()
	return _u
}

// SetRecipeID sets the "recipe_id" field.
func (_u *GroceryUpdate) SetRecipeID(v uuid.UUID) *GroceryUpdate {
	_u.mutation.SetRecipeID(v)
	return _u
}

// SetNillableRecipeID sets the "recipe_id" field if the given value is not nil.
func (_u *GroceryUpdate) SetNillableRecipeID(v *uuid.UUID) *GroceryUpdate {
	if v != nil {
		_u.SetRecipeID(*v)
	}
	return _u
}

// ClearRecipeID clears the value of the "recipe_id" field.
func (_u *GroceryUpdate) ClearRecipeID() *GroceryUpdate {
	_u.mutation.ClearRecipeID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroceryUpdate) SetUser(v *User) *GroceryUpdate {
	return _u.SetUserID(v.ID)
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (_u *GroceryUpdate) SetRecipe(v *Recipe) *GroceryUpdate {
	return _u.SetRecipeID(v.ID)
}

// Mutation returns the GroceryMutation object of the builder.
func (_u *GroceryUpdate) Mutation() *GroceryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroceryUpdate) ClearUser() *GroceryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (_u *GroceryUpdate) ClearRecipe() *GroceryUpdate {
	_u.mutation.ClearRecipe()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroceryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroceryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroceryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroceryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroceryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Grocery.user"`)
	}
	return nil
}

func (_u *GroceryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grocery.Table, grocery.Columns, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grocery.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(grocery.FieldUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(grocery.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(grocery.FieldQuantity, field.TypeFloat64, value)
	}
	if _u.mutation.QuantityCleared() {
		_spec.ClearField(grocery.FieldQuantity, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(grocery.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(grocery.FieldTag, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.UserTable,
			Columns: []string{grocery.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.UserTable,
			Columns: []string{grocery.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.RecipeTable,
			Columns: []string{grocery.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.RecipeTable,
			Columns: []string{grocery.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroceryUpdateOne is the builder for updating a single Grocery entity.
type GroceryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroceryMutation
}

// SetUserID sets the "user_id" field.
func (_u *GroceryUpdateOne) SetUserID(v int) *GroceryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableUserID(v *int) *GroceryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *GroceryUpdateOne) SetName(v string) *GroceryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableName(v *string) *GroceryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *GroceryUpdateOne) SetUnit(v string) *GroceryUpdateOne {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableUnit(v *string) *GroceryUpdateOne {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *GroceryUpdateOne) SetQuantity(v float64) *GroceryUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableQuantity(v *float64) *GroceryUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *GroceryUpdateOne) AddQuantity(v float64) *GroceryUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// ClearQuantity clears the value of the "quantity" field.
func (_u *GroceryUpdateOne) ClearQuantity() *GroceryUpdateOne {
	_u.mutation.ClearQuantity()
	return _u
}

// SetTag sets the "tag" field.
func (_u *GroceryUpdateOne) SetTag(v string) *GroceryUpdateOne {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableTag(v *string) *GroceryUpdateOne {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// ClearTag clears the value of the "tag" field.
func (_u *GroceryUpdateOne) ClearTag() *GroceryUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// SetRecipeID sets the "recipe_id" field.
func (_u *GroceryUpdateOne) SetRecipeID(v uuid.UUID) *GroceryUpdateOne {
	_u.mutation.SetRecipeID(v)
	return _u
}

// SetNillableRecipeID sets the "recipe_id" field if the given value is not nil.
func (_u *GroceryUpdateOne) SetNillableRecipeID(v *uuid.UUID) *GroceryUpdateOne {
	if v != nil {
		_u.SetRecipeID(*v)
	}
	return _u
}

// ClearRecipeID clears the value of the "recipe_id" field.
func (_u *GroceryUpdateOne) ClearRecipeID() *GroceryUpdateOne {
	_u.mutation.ClearRecipeID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroceryUpdateOne) SetUser(v *User) *GroceryUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (_u *GroceryUpdateOne) SetRecipe(v *Recipe) *GroceryUpdateOne {
	return _u.SetRecipeID(v.ID)
}

// Mutation returns the GroceryMutation object of the builder.
func (_u *GroceryUpdateOne) Mutation() *GroceryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroceryUpdateOne) ClearUser() *GroceryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (_u *GroceryUpdateOne) ClearRecipe() *GroceryUpdateOne {
	_u.mutation.ClearRecipe()
	return _u
}

// Where appends a list predicates to the GroceryUpdate builder.
func (_u *GroceryUpdateOne) Where(ps ...predicate.Grocery) *GroceryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroceryUpdateOne) Select(field string, fields ...string) *GroceryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Grocery entity.
func (_u *GroceryUpdateOne) Save(ctx context.Context) (*Grocery, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroceryUpdateOne) SaveX(ctx context.Context) *Grocery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroceryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroceryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroceryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Grocery.user"`)
	}
	return nil
}

func (_u *GroceryUpdateOne) sqlSave(ctx context.Context) (_node *Grocery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grocery.Table, grocery.Columns, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Grocery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grocery.FieldID)
		for _, f := range fields {
			if !grocery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grocery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grocery.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(grocery.FieldUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(grocery.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(grocery.FieldQuantity, field.TypeFloat64, value)
	}
	if _u.mutation.QuantityCleared() {
		_spec.ClearField(grocery.FieldQuantity, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(grocery.FieldTag, field.TypeString, value)
	}
	if _u.mutation.TagCleared() {
		_spec.ClearField(grocery.FieldTag, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.UserTable,
			Columns: []string{grocery.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.UserTable,
			Columns: []string{grocery.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.RecipeTable,
			Columns: []string{grocery.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.RecipeTable,
			Columns: []string{grocery.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Grocery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
