// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danirisdiandita/malas-monorepo/api/ent/grocery"
	"github.com/danirisdiandita/malas-monorepo/api/ent/user"
	"github.com/google/uuid"
)

// GroceryCreate is the builder for creating a Grocery entity.
type GroceryCreate struct {
	config
	mutation *GroceryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *GroceryCreate) SetUserID(v int) *GroceryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *GroceryCreate) SetName(v string) *GroceryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetUnit sets the "unit" field.
func (_c *GroceryCreate) SetUnit(v string) *GroceryCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetTag sets the "tag" field.
func (_c *GroceryCreate) SetTag(v string) *GroceryCreate {
	_c.mutation.SetTag(v)
	return _c
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_c *GroceryCreate) SetNillableTag(v *string) *GroceryCreate {
	if v != nil {
		_c.SetTag(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroceryCreate) SetID(v uuid.UUID) *GroceryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroceryCreate) SetNillableID(v *uuid.UUID) *GroceryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *GroceryCreate) SetUser(v *User) *GroceryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the GroceryMutation object of the builder.
func (_c *GroceryCreate) Mutation() *GroceryMutation {
	return _c.mutation
}

// Save creates the Grocery in the database.
func (_c *GroceryCreate) Save(ctx context.Context) (*Grocery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroceryCreate) SaveX(ctx context.Context) *Grocery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroceryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroceryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroceryCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := grocery.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroceryCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Grocery.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Grocery.name"`)}
	}
	if _, ok := _c.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "Grocery.unit"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Grocery.user"`)}
	}
	return nil
}

func (_c *GroceryCreate) sqlSave(ctx context.Context) (*Grocery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroceryCreate) createSpec() (*Grocery, *sqlgraph.CreateSpec) {
	var (
		_node = &Grocery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grocery.Table, sqlgraph.NewFieldSpec(grocery.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(grocery.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(grocery.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.Tag(); ok {
		_spec.SetField(grocery.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grocery.UserTable,
			Columns: []string{grocery.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroceryCreateBulk is the builder for creating many Grocery entities in bulk.
type GroceryCreateBulk struct {
	config
	err      error
	builders []*GroceryCreate
}

// Save creates the Grocery entities in the database.
func (_c *GroceryCreateBulk) Save(ctx context.Context) ([]*Grocery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Grocery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroceryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroceryCreateBulk) SaveX(ctx context.Context) []*Grocery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroceryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroceryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
