// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/danirisdiandita/malas-monorepo/api/ent/grocery"
	"github.com/danirisdiandita/malas-monorepo/api/ent/user"
	"github.com/google/uuid"
)

// Grocery is the model entity for the Grocery schema.
type Grocery struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Unit holds the value of the "unit" field.
	Unit string `json:"unit,omitempty"`
	// Tag holds the value of the "tag" field.
	Tag string `json:"tag,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroceryQuery when eager-loading is set.
	Edges        GroceryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroceryEdges holds the relations/edges for other nodes in the graph.
type GroceryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroceryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Grocery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grocery.FieldUserID:
			values[i] = new(sql.NullInt64)
		case grocery.FieldName, grocery.FieldUnit, grocery.FieldTag:
			values[i] = new(sql.NullString)
		case grocery.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Grocery fields.
func (_m *Grocery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grocery.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case grocery.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case grocery.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case grocery.FieldUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit", values[i])
			} else if value.Valid {
				_m.Unit = value.String
			}
		case grocery.FieldTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag", values[i])
			} else if value.Valid {
				_m.Tag = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Grocery.
// This includes values selected through modifiers, order, etc.
func (_m *Grocery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Grocery entity.
func (_m *Grocery) QueryUser() *UserQuery {
	return NewGroceryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Grocery.
// Note that you need to call Grocery.Unwrap() before calling this method if this Grocery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Grocery) Update() *GroceryUpdateOne {
	return NewGroceryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Grocery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Grocery) Unwrap() *Grocery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Grocery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Grocery) String() string {
	var builder strings.Builder
	builder.WriteString("Grocery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("unit=")
	builder.WriteString(_m.Unit)
	builder.WriteString(", ")
	builder.WriteString("tag=")
	builder.WriteString(_m.Tag)
	builder.WriteByte(')')
	return builder.String()
}

// Groceries is a parsable slice of Grocery.
type Groceries []*Grocery
