// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danirisdiandita/malas-monorepo/api/ent/mealcalendarentry"
	"github.com/danirisdiandita/malas-monorepo/api/ent/predicate"
)

// MealCalendarEntryDelete is the builder for deleting a MealCalendarEntry entity.
type MealCalendarEntryDelete struct {
	config
	hooks    []Hook
	mutation *MealCalendarEntryMutation
}

// Where appends a list predicates to the MealCalendarEntryDelete builder.
func (_d *MealCalendarEntryDelete) Where(ps ...predicate.MealCalendarEntry) *MealCalendarEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MealCalendarEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MealCalendarEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MealCalendarEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mealcalendarentry.Table, sqlgraph.NewFieldSpec(mealcalendarentry.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MealCalendarEntryDeleteOne is the builder for deleting a single MealCalendarEntry entity.
type MealCalendarEntryDeleteOne struct {
	_d *MealCalendarEntryDelete
}

// Where appends a list predicates to the MealCalendarEntryDelete builder.
func (_d *MealCalendarEntryDeleteOne) Where(ps ...predicate.MealCalendarEntry) *MealCalendarEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MealCalendarEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mealcalendarentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MealCalendarEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
