// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danirisdiandita/malas-monorepo/api/ent/predicate"
	"github.com/danirisdiandita/malas-monorepo/api/ent/revenuecatidentity"
)

// RevenueCatIdentityDelete is the builder for deleting a RevenueCatIdentity entity.
type RevenueCatIdentityDelete struct {
	config
	hooks    []Hook
	mutation *RevenueCatIdentityMutation
}

// Where appends a list predicates to the RevenueCatIdentityDelete builder.
func (_d *RevenueCatIdentityDelete) Where(ps ...predicate.RevenueCatIdentity) *RevenueCatIdentityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RevenueCatIdentityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RevenueCatIdentityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RevenueCatIdentityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(revenuecatidentity.Table, sqlgraph.NewFieldSpec(revenuecatidentity.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RevenueCatIdentityDeleteOne is the builder for deleting a single RevenueCatIdentity entity.
type RevenueCatIdentityDeleteOne struct {
	_d *RevenueCatIdentityDelete
}

// Where appends a list predicates to the RevenueCatIdentityDelete builder.
func (_d *RevenueCatIdentityDeleteOne) Where(ps ...predicate.RevenueCatIdentity) *RevenueCatIdentityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RevenueCatIdentityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{revenuecatidentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RevenueCatIdentityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
