// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danirisdiandita/malas-monorepo/api/ent/revenuecatidentity"
	"github.com/danirisdiandita/malas-monorepo/api/ent/user"
)

// RevenueCatIdentityCreate is the builder for creating a RevenueCatIdentity entity.
type RevenueCatIdentityCreate struct {
	config
	mutation *RevenueCatIdentityMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *RevenueCatIdentityCreate) SetUserID(v int) *RevenueCatIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRcAppUserID sets the "rc_app_user_id" field.
func (_c *RevenueCatIdentityCreate) SetRcAppUserID(v string) *RevenueCatIdentityCreate {
	_c.mutation.SetRcAppUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RevenueCatIdentityCreate) SetCreatedAt(v time.Time) *RevenueCatIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RevenueCatIdentityCreate) SetNillableCreatedAt(v *time.Time) *RevenueCatIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RevenueCatIdentityCreate) SetUpdatedAt(v time.Time) *RevenueCatIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RevenueCatIdentityCreate) SetNillableUpdatedAt(v *time.Time) *RevenueCatIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RevenueCatIdentityCreate) SetUser(v *User) *RevenueCatIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RevenueCatIdentityMutation object of the builder.
func (_c *RevenueCatIdentityCreate) Mutation() *RevenueCatIdentityMutation {
	return _c.mutation
}

// Save creates the RevenueCatIdentity in the database.
func (_c *RevenueCatIdentityCreate) Save(ctx context.Context) (*RevenueCatIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RevenueCatIdentityCreate) SaveX(ctx context.Context) *RevenueCatIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RevenueCatIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RevenueCatIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RevenueCatIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := revenuecatidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := revenuecatidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RevenueCatIdentityCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RevenueCatIdentity.user_id"`)}
	}
	if _, ok := _c.mutation.RcAppUserID(); !ok {
		return &ValidationError{Name: "rc_app_user_id", err: errors.New(`ent: missing required field "RevenueCatIdentity.rc_app_user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RevenueCatIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RevenueCatIdentity.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RevenueCatIdentity.user"`)}
	}
	return nil
}

func (_c *RevenueCatIdentityCreate) sqlSave(ctx context.Context) (*RevenueCatIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RevenueCatIdentityCreate) createSpec() (*RevenueCatIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &RevenueCatIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(revenuecatidentity.Table, sqlgraph.NewFieldSpec(revenuecatidentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RcAppUserID(); ok {
		_spec.SetField(revenuecatidentity.FieldRcAppUserID, field.TypeString, value)
		_node.RcAppUserID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(revenuecatidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(revenuecatidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   revenuecatidentity.UserTable,
			Columns: []string{revenuecatidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RevenueCatIdentityCreateBulk is the builder for creating many RevenueCatIdentity entities in bulk.
type RevenueCatIdentityCreateBulk struct {
	config
	err      error
	builders []*RevenueCatIdentityCreate
}

// Save creates the RevenueCatIdentity entities in the database.
func (_c *RevenueCatIdentityCreateBulk) Save(ctx context.Context) ([]*RevenueCatIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RevenueCatIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RevenueCatIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RevenueCatIdentityCreateBulk) SaveX(ctx context.Context) []*RevenueCatIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RevenueCatIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RevenueCatIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
