// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/danirisdiandita/malas-monorepo/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserID, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldEndDate, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStatus, v))
}

// RcAppUserID applies equality check predicate on the "rc_app_user_id" field. It's identical to RcAppUserIDEQ.
func RcAppUserID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcAppUserID, v))
}

// RcEnvironment applies equality check predicate on the "rc_environment" field. It's identical to RcEnvironmentEQ.
func RcEnvironment(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcEnvironment, v))
}

// RcProductID applies equality check predicate on the "rc_product_id" field. It's identical to RcProductIDEQ.
func RcProductID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcProductID, v))
}

// RcStore applies equality check predicate on the "rc_store" field. It's identical to RcStoreEQ.
func RcStore(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcStore, v))
}

// Credit applies equality check predicate on the "credit" field. It's identical to CreditEQ.
func Credit(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCredit, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUserID, vs...))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldStartDate))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldEndDate))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldStatus, v))
}

// RcAppUserIDEQ applies the EQ predicate on the "rc_app_user_id" field.
func RcAppUserIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcAppUserID, v))
}

// RcAppUserIDNEQ applies the NEQ predicate on the "rc_app_user_id" field.
func RcAppUserIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRcAppUserID, v))
}

// RcAppUserIDIn applies the In predicate on the "rc_app_user_id" field.
func RcAppUserIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRcAppUserID, vs...))
}

// RcAppUserIDNotIn applies the NotIn predicate on the "rc_app_user_id" field.
func RcAppUserIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRcAppUserID, vs...))
}

// RcAppUserIDGT applies the GT predicate on the "rc_app_user_id" field.
func RcAppUserIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRcAppUserID, v))
}

// RcAppUserIDGTE applies the GTE predicate on the "rc_app_user_id" field.
func RcAppUserIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRcAppUserID, v))
}

// RcAppUserIDLT applies the LT predicate on the "rc_app_user_id" field.
func RcAppUserIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRcAppUserID, v))
}

// RcAppUserIDLTE applies the LTE predicate on the "rc_app_user_id" field.
func RcAppUserIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRcAppUserID, v))
}

// RcAppUserIDContains applies the Contains predicate on the "rc_app_user_id" field.
func RcAppUserIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRcAppUserID, v))
}

// RcAppUserIDHasPrefix applies the HasPrefix predicate on the "rc_app_user_id" field.
func RcAppUserIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRcAppUserID, v))
}

// RcAppUserIDHasSuffix applies the HasSuffix predicate on the "rc_app_user_id" field.
func RcAppUserIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRcAppUserID, v))
}

// RcAppUserIDEqualFold applies the EqualFold predicate on the "rc_app_user_id" field.
func RcAppUserIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRcAppUserID, v))
}

// RcAppUserIDContainsFold applies the ContainsFold predicate on the "rc_app_user_id" field.
func RcAppUserIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRcAppUserID, v))
}

// RcEnvironmentEQ applies the EQ predicate on the "rc_environment" field.
func RcEnvironmentEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcEnvironment, v))
}

// RcEnvironmentNEQ applies the NEQ predicate on the "rc_environment" field.
func RcEnvironmentNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRcEnvironment, v))
}

// RcEnvironmentIn applies the In predicate on the "rc_environment" field.
func RcEnvironmentIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRcEnvironment, vs...))
}

// RcEnvironmentNotIn applies the NotIn predicate on the "rc_environment" field.
func RcEnvironmentNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRcEnvironment, vs...))
}

// RcEnvironmentGT applies the GT predicate on the "rc_environment" field.
func RcEnvironmentGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRcEnvironment, v))
}

// RcEnvironmentGTE applies the GTE predicate on the "rc_environment" field.
func RcEnvironmentGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRcEnvironment, v))
}

// RcEnvironmentLT applies the LT predicate on the "rc_environment" field.
func RcEnvironmentLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRcEnvironment, v))
}

// RcEnvironmentLTE applies the LTE predicate on the "rc_environment" field.
func RcEnvironmentLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRcEnvironment, v))
}

// RcEnvironmentContains applies the Contains predicate on the "rc_environment" field.
func RcEnvironmentContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRcEnvironment, v))
}

// RcEnvironmentHasPrefix applies the HasPrefix predicate on the "rc_environment" field.
func RcEnvironmentHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRcEnvironment, v))
}

// RcEnvironmentHasSuffix applies the HasSuffix predicate on the "rc_environment" field.
func RcEnvironmentHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRcEnvironment, v))
}

// RcEnvironmentEqualFold applies the EqualFold predicate on the "rc_environment" field.
func RcEnvironmentEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRcEnvironment, v))
}

// RcEnvironmentContainsFold applies the ContainsFold predicate on the "rc_environment" field.
func RcEnvironmentContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRcEnvironment, v))
}

// RcProductIDEQ applies the EQ predicate on the "rc_product_id" field.
func RcProductIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcProductID, v))
}

// RcProductIDNEQ applies the NEQ predicate on the "rc_product_id" field.
func RcProductIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRcProductID, v))
}

// RcProductIDIn applies the In predicate on the "rc_product_id" field.
func RcProductIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRcProductID, vs...))
}

// RcProductIDNotIn applies the NotIn predicate on the "rc_product_id" field.
func RcProductIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRcProductID, vs...))
}

// RcProductIDGT applies the GT predicate on the "rc_product_id" field.
func RcProductIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRcProductID, v))
}

// RcProductIDGTE applies the GTE predicate on the "rc_product_id" field.
func RcProductIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRcProductID, v))
}

// RcProductIDLT applies the LT predicate on the "rc_product_id" field.
func RcProductIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRcProductID, v))
}

// RcProductIDLTE applies the LTE predicate on the "rc_product_id" field.
func RcProductIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRcProductID, v))
}

// RcProductIDContains applies the Contains predicate on the "rc_product_id" field.
func RcProductIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRcProductID, v))
}

// RcProductIDHasPrefix applies the HasPrefix predicate on the "rc_product_id" field.
func RcProductIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRcProductID, v))
}

// RcProductIDHasSuffix applies the HasSuffix predicate on the "rc_product_id" field.
func RcProductIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRcProductID, v))
}

// RcProductIDEqualFold applies the EqualFold predicate on the "rc_product_id" field.
func RcProductIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRcProductID, v))
}

// RcProductIDContainsFold applies the ContainsFold predicate on the "rc_product_id" field.
func RcProductIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRcProductID, v))
}

// RcStoreEQ applies the EQ predicate on the "rc_store" field.
func RcStoreEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRcStore, v))
}

// RcStoreNEQ applies the NEQ predicate on the "rc_store" field.
func RcStoreNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRcStore, v))
}

// RcStoreIn applies the In predicate on the "rc_store" field.
func RcStoreIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRcStore, vs...))
}

// RcStoreNotIn applies the NotIn predicate on the "rc_store" field.
func RcStoreNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRcStore, vs...))
}

// RcStoreGT applies the GT predicate on the "rc_store" field.
func RcStoreGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRcStore, v))
}

// RcStoreGTE applies the GTE predicate on the "rc_store" field.
func RcStoreGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRcStore, v))
}

// RcStoreLT applies the LT predicate on the "rc_store" field.
func RcStoreLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRcStore, v))
}

// RcStoreLTE applies the LTE predicate on the "rc_store" field.
func RcStoreLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRcStore, v))
}

// RcStoreContains applies the Contains predicate on the "rc_store" field.
func RcStoreContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRcStore, v))
}

// RcStoreHasPrefix applies the HasPrefix predicate on the "rc_store" field.
func RcStoreHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRcStore, v))
}

// RcStoreHasSuffix applies the HasSuffix predicate on the "rc_store" field.
func RcStoreHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRcStore, v))
}

// RcStoreEqualFold applies the EqualFold predicate on the "rc_store" field.
func RcStoreEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRcStore, v))
}

// RcStoreContainsFold applies the ContainsFold predicate on the "rc_store" field.
func RcStoreContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRcStore, v))
}

// CreditEQ applies the EQ predicate on the "credit" field.
func CreditEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCredit, v))
}

// CreditNEQ applies the NEQ predicate on the "credit" field.
func CreditNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCredit, v))
}

// CreditIn applies the In predicate on the "credit" field.
func CreditIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCredit, vs...))
}

// CreditNotIn applies the NotIn predicate on the "credit" field.
func CreditNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCredit, vs...))
}

// CreditGT applies the GT predicate on the "credit" field.
func CreditGT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCredit, v))
}

// CreditGTE applies the GTE predicate on the "credit" field.
func CreditGTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCredit, v))
}

// CreditLT applies the LT predicate on the "credit" field.
func CreditLT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCredit, v))
}

// CreditLTE applies the LTE predicate on the "credit" field.
func CreditLTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCredit, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
