// Code generated by ent, DO NOT EDIT.

package recipe

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the recipe type in the database.
	Label = "recipe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFolderID holds the string denoting the folder_id field in the database.
	FieldFolderID = "folder_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldServings holds the string denoting the servings field in the database.
	FieldServings = "servings"
	// FieldProcessMinutes holds the string denoting the process_minutes field in the database.
	FieldProcessMinutes = "process_minutes"
	// FieldIngredients holds the string denoting the ingredients field in the database.
	FieldIngredients = "ingredients"
	// FieldInstructions holds the string denoting the instructions field in the database.
	FieldInstructions = "instructions"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldImportStatus holds the string denoting the import_status field in the database.
	FieldImportStatus = "import_status"
	// FieldImportError holds the string denoting the import_error field in the database.
	FieldImportError = "import_error"
	// FieldProcessingAt holds the string denoting the processing_at field in the database.
	FieldProcessingAt = "processing_at"
	// FieldImportWebhook holds the string denoting the import_webhook field in the database.
	FieldImportWebhook = "import_webhook"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldImageS3Key holds the string denoting the image_s3_key field in the database.
	FieldImageS3Key = "image_s3_key"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldWebhookID holds the string denoting the webhook_id field in the database.
	FieldWebhookID = "webhook_id"
	// FieldRawSourcePayload holds the string denoting the raw_source_payload field in the database.
	FieldRawSourcePayload = "raw_source_payload"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeFolder holds the string denoting the folder edge name in mutations.
	EdgeFolder = "folder"
	// Table holds the table name of the recipe in the database.
	Table = "recipes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "recipes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// FolderTable is the table that holds the folder relation/edge.
	FolderTable = "recipes"
	// FolderInverseTable is the table name for the Folder entity.
	// It exists in this package in order to avoid circular dependency with the "folder" package.
	FolderInverseTable = "folders"
	// FolderColumn is the table column denoting the folder relation/edge.
	FolderColumn = "folder_id"
)

// Columns holds all SQL columns for recipe fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldFolderID,
	FieldName,
	FieldServings,
	FieldProcessMinutes,
	FieldIngredients,
	FieldInstructions,
	FieldTags,
	FieldImportStatus,
	FieldImportError,
	FieldProcessingAt,
	FieldImportWebhook,
	FieldCreatedAt,
	FieldRating,
	FieldNotes,
	FieldImageS3Key,
	FieldURL,
	FieldSource,
	FieldWebhookID,
	FieldRawSourcePayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ImportStatus defines the type for the "import_status" enum field.
type ImportStatus string

// ImportStatusDone is the default value of the ImportStatus enum.
const DefaultImportStatus = ImportStatusDone

// ImportStatus values.
const (
	ImportStatusLooking ImportStatus = "looking"
	ImportStatusMaking  ImportStatus = "making"
	ImportStatusDone    ImportStatus = "done"
	ImportStatusFailed  ImportStatus = "failed"
)

func (is ImportStatus) String() string {
	return string(is)
}

// ImportStatusValidator is a validator for the "import_status" field enum values. It is called by the builders before save.
func ImportStatusValidator(is ImportStatus) error {
	switch is {
	case ImportStatusLooking, ImportStatusMaking, ImportStatusDone, ImportStatusFailed:
		return nil
	default:
		return fmt.Errorf("recipe: invalid enum value for import_status field: %q", is)
	}
}

// OrderOption defines the ordering options for the Recipe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFolderID orders the results by the folder_id field.
func ByFolderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByServings orders the results by the servings field.
func ByServings(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServings, opts...).ToFunc()
}

// ByProcessMinutes orders the results by the process_minutes field.
func ByProcessMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessMinutes, opts...).ToFunc()
}

// ByInstructions orders the results by the instructions field.
func ByInstructions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructions, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByImportStatus orders the results by the import_status field.
func ByImportStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportStatus, opts...).ToFunc()
}

// ByImportError orders the results by the import_error field.
func ByImportError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportError, opts...).ToFunc()
}

// ByProcessingAt orders the results by the processing_at field.
func ByProcessingAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessingAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByImageS3Key orders the results by the image_s3_key field.
func ByImageS3Key(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageS3Key, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByWebhookID orders the results by the webhook_id field.
func ByWebhookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByFolderField orders the results by folder field.
func ByFolderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFolderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newFolderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FolderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FolderTable, FolderColumn),
	)
}
