// Code generated by ent, DO NOT EDIT.

package recipe

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/danirisdiandita/malas-monorepo/api/ent/predicate"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldUserID, v))
}

// FolderID applies equality check predicate on the "folder_id" field. It's identical to FolderIDEQ.
func FolderID(v uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldFolderID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldName, v))
}

// Servings applies equality check predicate on the "servings" field. It's identical to ServingsEQ.
func Servings(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldServings, v))
}

// ProcessMinutes applies equality check predicate on the "process_minutes" field. It's identical to ProcessMinutesEQ.
func ProcessMinutes(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldProcessMinutes, v))
}

// Instructions applies equality check predicate on the "instructions" field. It's identical to InstructionsEQ.
func Instructions(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldInstructions, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldTags, v))
}

// ImportError applies equality check predicate on the "import_error" field. It's identical to ImportErrorEQ.
func ImportError(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldImportError, v))
}

// ProcessingAt applies equality check predicate on the "processing_at" field. It's identical to ProcessingAtEQ.
func ProcessingAt(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldProcessingAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldCreatedAt, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldRating, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldNotes, v))
}

// ImageS3Key applies equality check predicate on the "image_s3_key" field. It's identical to ImageS3KeyEQ.
func ImageS3Key(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldImageS3Key, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldURL, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldSource, v))
}

// WebhookID applies equality check predicate on the "webhook_id" field. It's identical to WebhookIDEQ.
func WebhookID(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldWebhookID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldUserID, vs...))
}

// FolderIDEQ applies the EQ predicate on the "folder_id" field.
func FolderIDEQ(v uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldFolderID, v))
}

// FolderIDNEQ applies the NEQ predicate on the "folder_id" field.
func FolderIDNEQ(v uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldFolderID, v))
}

// FolderIDIn applies the In predicate on the "folder_id" field.
func FolderIDIn(vs ...uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldFolderID, vs...))
}

// FolderIDNotIn applies the NotIn predicate on the "folder_id" field.
func FolderIDNotIn(vs ...uuid.UUID) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldFolderID, vs...))
}

// FolderIDIsNil applies the IsNil predicate on the "folder_id" field.
func FolderIDIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldFolderID))
}

// FolderIDNotNil applies the NotNil predicate on the "folder_id" field.
func FolderIDNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldFolderID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldName, v))
}

// ServingsEQ applies the EQ predicate on the "servings" field.
func ServingsEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldServings, v))
}

// ServingsNEQ applies the NEQ predicate on the "servings" field.
func ServingsNEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldServings, v))
}

// ServingsIn applies the In predicate on the "servings" field.
func ServingsIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldServings, vs...))
}

// ServingsNotIn applies the NotIn predicate on the "servings" field.
func ServingsNotIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldServings, vs...))
}

// ServingsGT applies the GT predicate on the "servings" field.
func ServingsGT(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldServings, v))
}

// ServingsGTE applies the GTE predicate on the "servings" field.
func ServingsGTE(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldServings, v))
}

// ServingsLT applies the LT predicate on the "servings" field.
func ServingsLT(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldServings, v))
}

// ServingsLTE applies the LTE predicate on the "servings" field.
func ServingsLTE(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldServings, v))
}

// ProcessMinutesEQ applies the EQ predicate on the "process_minutes" field.
func ProcessMinutesEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldProcessMinutes, v))
}

// ProcessMinutesNEQ applies the NEQ predicate on the "process_minutes" field.
func ProcessMinutesNEQ(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldProcessMinutes, v))
}

// ProcessMinutesIn applies the In predicate on the "process_minutes" field.
func ProcessMinutesIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldProcessMinutes, vs...))
}

// ProcessMinutesNotIn applies the NotIn predicate on the "process_minutes" field.
func ProcessMinutesNotIn(vs ...int) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldProcessMinutes, vs...))
}

// ProcessMinutesGT applies the GT predicate on the "process_minutes" field.
func ProcessMinutesGT(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldProcessMinutes, v))
}

// ProcessMinutesGTE applies the GTE predicate on the "process_minutes" field.
func ProcessMinutesGTE(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldProcessMinutes, v))
}

// ProcessMinutesLT applies the LT predicate on the "process_minutes" field.
func ProcessMinutesLT(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldProcessMinutes, v))
}

// ProcessMinutesLTE applies the LTE predicate on the "process_minutes" field.
func ProcessMinutesLTE(v int) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldProcessMinutes, v))
}

// InstructionsEQ applies the EQ predicate on the "instructions" field.
func InstructionsEQ(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldInstructions, v))
}

// InstructionsNEQ applies the NEQ predicate on the "instructions" field.
func InstructionsNEQ(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldInstructions, v))
}

// InstructionsIn applies the In predicate on the "instructions" field.
func InstructionsIn(vs ...pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldInstructions, vs...))
}

// InstructionsNotIn applies the NotIn predicate on the "instructions" field.
func InstructionsNotIn(vs ...pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldInstructions, vs...))
}

// InstructionsGT applies the GT predicate on the "instructions" field.
func InstructionsGT(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldInstructions, v))
}

// InstructionsGTE applies the GTE predicate on the "instructions" field.
func InstructionsGTE(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldInstructions, v))
}

// InstructionsLT applies the LT predicate on the "instructions" field.
func InstructionsLT(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldInstructions, v))
}

// InstructionsLTE applies the LTE predicate on the "instructions" field.
func InstructionsLTE(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldInstructions, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v pq.StringArray) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldTags))
}

// ImportStatusEQ applies the EQ predicate on the "import_status" field.
func ImportStatusEQ(v ImportStatus) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldImportStatus, v))
}

// ImportStatusNEQ applies the NEQ predicate on the "import_status" field.
func ImportStatusNEQ(v ImportStatus) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldImportStatus, v))
}

// ImportStatusIn applies the In predicate on the "import_status" field.
func ImportStatusIn(vs ...ImportStatus) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldImportStatus, vs...))
}

// ImportStatusNotIn applies the NotIn predicate on the "import_status" field.
func ImportStatusNotIn(vs ...ImportStatus) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldImportStatus, vs...))
}

// ImportErrorEQ applies the EQ predicate on the "import_error" field.
func ImportErrorEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldImportError, v))
}

// ImportErrorNEQ applies the NEQ predicate on the "import_error" field.
func ImportErrorNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldImportError, v))
}

// ImportErrorIn applies the In predicate on the "import_error" field.
func ImportErrorIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldImportError, vs...))
}

// ImportErrorNotIn applies the NotIn predicate on the "import_error" field.
func ImportErrorNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldImportError, vs...))
}

// ImportErrorGT applies the GT predicate on the "import_error" field.
func ImportErrorGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldImportError, v))
}

// ImportErrorGTE applies the GTE predicate on the "import_error" field.
func ImportErrorGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldImportError, v))
}

// ImportErrorLT applies the LT predicate on the "import_error" field.
func ImportErrorLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldImportError, v))
}

// ImportErrorLTE applies the LTE predicate on the "import_error" field.
func ImportErrorLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldImportError, v))
}

// ImportErrorContains applies the Contains predicate on the "import_error" field.
func ImportErrorContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldImportError, v))
}

// ImportErrorHasPrefix applies the HasPrefix predicate on the "import_error" field.
func ImportErrorHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldImportError, v))
}

// ImportErrorHasSuffix applies the HasSuffix predicate on the "import_error" field.
func ImportErrorHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldImportError, v))
}

// ImportErrorIsNil applies the IsNil predicate on the "import_error" field.
func ImportErrorIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldImportError))
}

// ImportErrorNotNil applies the NotNil predicate on the "import_error" field.
func ImportErrorNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldImportError))
}

// ImportErrorEqualFold applies the EqualFold predicate on the "import_error" field.
func ImportErrorEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldImportError, v))
}

// ImportErrorContainsFold applies the ContainsFold predicate on the "import_error" field.
func ImportErrorContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldImportError, v))
}

// ProcessingAtEQ applies the EQ predicate on the "processing_at" field.
func ProcessingAtEQ(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldProcessingAt, v))
}

// ProcessingAtNEQ applies the NEQ predicate on the "processing_at" field.
func ProcessingAtNEQ(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldProcessingAt, v))
}

// ProcessingAtIn applies the In predicate on the "processing_at" field.
func ProcessingAtIn(vs ...time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldProcessingAt, vs...))
}

// ProcessingAtNotIn applies the NotIn predicate on the "processing_at" field.
func ProcessingAtNotIn(vs ...time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldProcessingAt, vs...))
}

// ProcessingAtGT applies the GT predicate on the "processing_at" field.
func ProcessingAtGT(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldProcessingAt, v))
}

// ProcessingAtGTE applies the GTE predicate on the "processing_at" field.
func ProcessingAtGTE(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldProcessingAt, v))
}

// ProcessingAtLT applies the LT predicate on the "processing_at" field.
func ProcessingAtLT(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldProcessingAt, v))
}

// ProcessingAtLTE applies the LTE predicate on the "processing_at" field.
func ProcessingAtLTE(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldProcessingAt, v))
}

// ProcessingAtIsNil applies the IsNil predicate on the "processing_at" field.
func ProcessingAtIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldProcessingAt))
}

// ProcessingAtNotNil applies the NotNil predicate on the "processing_at" field.
func ProcessingAtNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldProcessingAt))
}

// ImportWebhookIsNil applies the IsNil predicate on the "import_webhook" field.
func ImportWebhookIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldImportWebhook))
}

// ImportWebhookNotNil applies the NotNil predicate on the "import_webhook" field.
func ImportWebhookNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldImportWebhook))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldCreatedAt, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float64) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldRating, v))
}

// RatingIsNil applies the IsNil predicate on the "rating" field.
func RatingIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldRating))
}

// RatingNotNil applies the NotNil predicate on the "rating" field.
func RatingNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldRating))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldNotes, v))
}

// ImageS3KeyEQ applies the EQ predicate on the "image_s3_key" field.
func ImageS3KeyEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldImageS3Key, v))
}

// ImageS3KeyNEQ applies the NEQ predicate on the "image_s3_key" field.
func ImageS3KeyNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldImageS3Key, v))
}

// ImageS3KeyIn applies the In predicate on the "image_s3_key" field.
func ImageS3KeyIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldImageS3Key, vs...))
}

// ImageS3KeyNotIn applies the NotIn predicate on the "image_s3_key" field.
func ImageS3KeyNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldImageS3Key, vs...))
}

// ImageS3KeyGT applies the GT predicate on the "image_s3_key" field.
func ImageS3KeyGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldImageS3Key, v))
}

// ImageS3KeyGTE applies the GTE predicate on the "image_s3_key" field.
func ImageS3KeyGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldImageS3Key, v))
}

// ImageS3KeyLT applies the LT predicate on the "image_s3_key" field.
func ImageS3KeyLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldImageS3Key, v))
}

// ImageS3KeyLTE applies the LTE predicate on the "image_s3_key" field.
func ImageS3KeyLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldImageS3Key, v))
}

// ImageS3KeyContains applies the Contains predicate on the "image_s3_key" field.
func ImageS3KeyContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldImageS3Key, v))
}

// ImageS3KeyHasPrefix applies the HasPrefix predicate on the "image_s3_key" field.
func ImageS3KeyHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldImageS3Key, v))
}

// ImageS3KeyHasSuffix applies the HasSuffix predicate on the "image_s3_key" field.
func ImageS3KeyHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldImageS3Key, v))
}

// ImageS3KeyIsNil applies the IsNil predicate on the "image_s3_key" field.
func ImageS3KeyIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldImageS3Key))
}

// ImageS3KeyNotNil applies the NotNil predicate on the "image_s3_key" field.
func ImageS3KeyNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldImageS3Key))
}

// ImageS3KeyEqualFold applies the EqualFold predicate on the "image_s3_key" field.
func ImageS3KeyEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldImageS3Key, v))
}

// ImageS3KeyContainsFold applies the ContainsFold predicate on the "image_s3_key" field.
func ImageS3KeyContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldImageS3Key, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldURL, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldSource, v))
}

// WebhookIDEQ applies the EQ predicate on the "webhook_id" field.
func WebhookIDEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEQ(FieldWebhookID, v))
}

// WebhookIDNEQ applies the NEQ predicate on the "webhook_id" field.
func WebhookIDNEQ(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNEQ(FieldWebhookID, v))
}

// WebhookIDIn applies the In predicate on the "webhook_id" field.
func WebhookIDIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldIn(FieldWebhookID, vs...))
}

// WebhookIDNotIn applies the NotIn predicate on the "webhook_id" field.
func WebhookIDNotIn(vs ...string) predicate.Recipe {
	return predicate.Recipe(sql.FieldNotIn(FieldWebhookID, vs...))
}

// WebhookIDGT applies the GT predicate on the "webhook_id" field.
func WebhookIDGT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGT(FieldWebhookID, v))
}

// WebhookIDGTE applies the GTE predicate on the "webhook_id" field.
func WebhookIDGTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldGTE(FieldWebhookID, v))
}

// WebhookIDLT applies the LT predicate on the "webhook_id" field.
func WebhookIDLT(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLT(FieldWebhookID, v))
}

// WebhookIDLTE applies the LTE predicate on the "webhook_id" field.
func WebhookIDLTE(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldLTE(FieldWebhookID, v))
}

// WebhookIDContains applies the Contains predicate on the "webhook_id" field.
func WebhookIDContains(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContains(FieldWebhookID, v))
}

// WebhookIDHasPrefix applies the HasPrefix predicate on the "webhook_id" field.
func WebhookIDHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasPrefix(FieldWebhookID, v))
}

// WebhookIDHasSuffix applies the HasSuffix predicate on the "webhook_id" field.
func WebhookIDHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldHasSuffix(FieldWebhookID, v))
}

// WebhookIDIsNil applies the IsNil predicate on the "webhook_id" field.
func WebhookIDIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldWebhookID))
}

// WebhookIDNotNil applies the NotNil predicate on the "webhook_id" field.
func WebhookIDNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldWebhookID))
}

// WebhookIDEqualFold applies the EqualFold predicate on the "webhook_id" field.
func WebhookIDEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldEqualFold(FieldWebhookID, v))
}

// WebhookIDContainsFold applies the ContainsFold predicate on the "webhook_id" field.
func WebhookIDContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(sql.FieldContainsFold(FieldWebhookID, v))
}

// RawSourcePayloadIsNil applies the IsNil predicate on the "raw_source_payload" field.
func RawSourcePayloadIsNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldIsNull(FieldRawSourcePayload))
}

// RawSourcePayloadNotNil applies the NotNil predicate on the "raw_source_payload" field.
func RawSourcePayloadNotNil() predicate.Recipe {
	return predicate.Recipe(sql.FieldNotNull(FieldRawSourcePayload))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFolder applies the HasEdge predicate on the "folder" edge.
func HasFolder() predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FolderTable, FolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFolderWith applies the HasEdge predicate on the "folder" edge with a given conditions (other predicates).
func HasFolderWith(preds ...predicate.Folder) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := newFolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroceries applies the HasEdge predicate on the "groceries" edge.
func HasGroceries() predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroceriesTable, GroceriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroceriesWith applies the HasEdge predicate on the "groceries" edge with a given conditions (other predicates).
func HasGroceriesWith(preds ...predicate.Grocery) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := newGroceriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(sql.NotPredicates(p))
}
